### ISSUE TITLE
programming files/sum_even_fibonacci.cc

### ISSUE THREAD

**Issue by jjbush11** [jjbush11/VERSO-Activity#11]
Description A clear and concise description of what the issue/bug is.

Steps to Reproduce

Expected Behavior: Sum all the even fibonacci numbers that are below 4,000,000

Actual Behavior: Doesn't exit code 0

Additional Information

Operating System: Darwin
Browser: Chrome

Possible Solution: Add return 0;

Priority How critical is this issue/bug? Low, medium, or high priority?
low

Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?
always

Impact What is the impact of this issue/bug? Low, medium, or high?
high, program doesn't run

**Comment by ogalexan** [comment]
Changed the int to compare against 0 not 1 for even
